### PR TITLE
Update so it works with Kubo v0.16.0-rc1

### PR DESCRIPTION
**Pull request by hsanjuan**

### CODE REVIEW

**Comment by hsanjuan** [comment]
Couldn't make it work with 0.15.0:

```
[17:13:47] ~/g/s/g/i/go-ds-s3 (release/v0.15.0|✚2) $ go build ./...
# github.com/ipfs/go-ipns
../../../../pkg/mod/github.com/ipfs/go-ipns@v0.1.2/record.go:49:19: undefined: peer.IDFromString
```

Seems this goes away with 0.16.0-rc1.
